(let ((noninteractive nil))
  (setq sane-perl-font-lock t)
  (add-to-list 'load-path ".")
  (add-to-list 'load-path "..")
  (setq htmlize-use-rgb-map 'force)
  (require 'htmlize)
  (require 'sane-perl-mode)
  (sane-perl-mode)
  (font-lock-fontify-buffer)
  (goto-char (point-min))
  (replace-string "bbb" "qqq")
;  (while (search-forward "bbb" nil t)
;    (replace-match "qqq"))
  (with-current-buffer (htmlize-buffer)
    (princ (buffer-string))))
